id: A7F2757D5
title: A Practice of Fulfilment and Confession to an Ocean of Oath-bound Protectors
type: translation
pechas:
- IC3360330
- I35B88630
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:41:10.786328
  last_modified_at: 2023-01-04 12:41:10.786352
  collections:
  - Jigme Lingpa Series
  - Works of Tibetan Masters
alignment_to_base:
  IC3360330/3798: BBED
  I35B88630/F442: BBED
